[package]
name = "joint_rs"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.8.0"
euclid = "0.20.1"
undo = "0.36.0"
petgraph = "0.4.13"
serde = "1.0.98"
serde_derive = "1.0.98"
